### ISSUE TITLE
CTA buttons clickable

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb.io#10]
With "cta" buttons, the link only opens when clicking the text of the button. Not when clicking in the button (but not the text). Bad experience for users as the button highlights on hover but it just feels like it doesnt work.

**Comment by Developerayo** [comment]
Hey @TheTanc can I jump on this?

**Comment by hacktivist123** [comment]
Hi, @TheTanc can you provide clarity on this issue so that I can work on it??

Thanks.

**Comment by TheTanc** [comment]
Hey, thanks for picking this up. The issue is no longer here, I should have closed this a long time ago :)
The problem was that certain buttons were buggy and clicking on them produced no results unless you specifically clicked on the text. 
With that said, we sorted this a long time ago so ill close the issue.

**Comment by hacktivist123** [comment]
Alright, my pleasure. I also applied for the role of a Technical Writer at QuestDB. Is there anything you could do for me?
