### ISSUE TITLE
Third-party tools

### ISSUE THREAD

**Issue by amyshwang** [questdb/questdb.io#1013]
Location:

![Image](https://user-images.githubusercontent.com/107401731/186206373-6a4e3c7e-93ad-4a2b-a40a-20dc3697cec9.png)

1. Overview page
    - Adding overview to highlight supported tools and "coming soon"
    - 
2. Missing tools to be added:

- [ ] redpanda #1387
- [ ] mindsdb
- [ ] cube.js 
Extract content form tutorials and add it to the sidebar

**Comment by amyshwang** [comment]
### Third-party tools overview page

QuestDB support many third-party tools to meet our users' need. The below is a summary of what we currently support and links to individual guides. We also include a list of tools that we are planning to support.

#### Supported tools
[alphabetical order of the list with links to guide page]
Question: alphabetical order or order based on popularity? 

- [Grafana](url): An observability and monitoring application
- [Kafka Connect](url): A event streaming tool
- [Prometheus](url): An open-source system monitoring and alerting toolkit
- [Telegraf](url): A plugin-driven server agent for collecting & reporting metrics
- 
#### Coming soon
The following are tools that we are planning to support, watch this space!
If your preferred tools are not on this list, please let us know on our [Slack community](link).

[alphabetical order of the list with links to those tools]

**Comment by amyshwang** [comment]
As discussed with @pswu11 - 
1. Try to create an overview page with minimum effort, in order to 
    - Introduce roadmap link
    - Show links to supported tools not having their own individual page yet
This can be an intermediary step, to see if it improves readability.

**Comment by argshook** [comment]
We now have https://questdb.io/docs/third-party-tools

in addition, we can mark sidebar element with custom tags, like `new` or similar.

Thus, closing the ticket.
