### ISSUE TITLE
Update - Capturing `like/llike` functions

### ISSUE THREAD

**Issue by amyshwang** [questdb/questdb.io#1078]
**Describe the requested changes:**

In the core repo QuestDB has two regex functions `like` and `ilike` that are not yet documented:
https://github.com/questdb/questdb/tree/master/core/src/main/java/io/questdb/griffin/engine/functions/regex

io.questdb.griffin.engine.functions.regex.LikeStrFunctionFactory
io.questdb.griffin.engine.functions.regex.ILikeStrFunctionFactory
io.questdb.griffin.engine.functions.regex.LikeCharFunctionFactory

The task involves:
Create a new section for each function, following the [template](https://github.com/questdb/questdb.io/blob/master/docs/__guidelines/template/function.md).

**Location:**
/docs/reference/operators/regex/

**Comment by orensaldanha** [comment]
Can I take this?
