### ISSUE TITLE
Update - adding regexp_replace function

### ISSUE THREAD

**Issue by amyshwang** [questdb/questdb.io#1081]
Describe the requested changes:

In the core repo QuestDB has `regexp_replace` function that is not yet documented:

[RegexpReplaceStrFunctionFactory.java](https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/griffin/engine/functions/regex/RegexpReplaceStrFunctionFactory.java)

The task involves:
Create a new section for each function, following the [template](https://github.com/questdb/questdb.io/blob/master/docs/__guidelines/template/function.md).

Location:
/docs/reference/operators/regex/

**Comment by AnkitaMalik22** [comment]
I would love to work on this issue
