### ISSUE TITLE
Update - Capture `power()` function

### ISSUE THREAD

**Issue by amyshwang** [questdb/questdb.io#1082]
Describe the requested changes:

In the core repo QuestDB has `power` function that is not yet documented:

[PowDoubleFunctionFactory.java](https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/griffin/engine/functions/math/PowDoubleFunctionFactory.java)

The task involves:
Create a new section for the function, following the [template](https://github.com/questdb/questdb.io/blob/master/docs/__guidelines/template/function.md).

Location:
[/docs/reference/operators/rege/](https://questdb.io/docs/reference/function/numeric/)

**Comment by sudiptog81** [comment]
WIll like to take this on!
