### ISSUE TITLE
Update - adding `base64()` function to docs

### ISSUE THREAD

**Issue by amyshwang** [questdb/questdb.io#1084]
Describe the requested changes:

In the core repo QuestDB has `base64()` function that is not yet documented:

[Base64FunctionFactory.java](https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/griffin/engine/functions/bin/Base64FunctionFactory.java)

The task involves:
Create a new section for each function, following the [template](https://github.com/questdb/questdb.io/blob/master/docs/__guidelines/template/function.md).

Location:
[/docs/reference/](https://questdb.io/docs/reference/function/text/)

**Comment by sudiptog81** [comment]
WIll like to take this on!
