### ISSUE TITLE
Update - adding `row_number` function 

### ISSUE THREAD

**Issue by amyshwang** [questdb/questdb.io#1096]
Describe the requested changes:

In the core repo QuestDB has [row_number() function](https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/griffin/engine/functions/analytic/RowNumberFunctionFactory.java) that is not yet documented.

The task involves:
Create a new section for the function, following the [template](https://github.com/questdb/questdb.io/blob/master/docs/__guidelines/template/function.md).
Provide useful example(s) to explain how to use it in QuestDB.

Location:
A new section in https://questdb.io/docs/reference/function/aggregation/

**Comment by Smartmind12** [comment]
Hey Could you assign this issue to me as i would like to work on it...Thanks!

**Comment by AbhishekTiwari23** [comment]
I want to contribute to this one, please assign

**Comment by amyshwang** [comment]
@AbhishekTiwari23 sorry - first come first serve - this is assigned to @Smartmind12. We have other tasks and you're more than welcome to pick another one!
