### ISSUE TITLE
Tutorial on Using QuestDB to Build a Crypto Trade Database in Julia

### ISSUE THREAD

**Issue by VanshajPoonia** [questdb/questdb.io#1121]
## My tutorial idea

I have created a tutorial on How to build a crypto price tracker that calls an API every minute and stores the prices of different coins with the help of Python and QuestDB.

I will be showing how to connect to Coinbase WebSockets in Julia to download trades that will be stored in a QuestDB table.

## Community vote

Please leave your feedback on this tutorial

👍 I need this! 🚀 I can help you!

**Comment by amyshwang** [comment]
Hi, thank you for your submission. 
We always encourage contribution of original content that has not already covered.

We already have at least one tutorial that is on a similar topic:
https://questdb.io/blog/2021/11/22/high-frequency-finance-introduction-julia-lang/

Based on your description, it seems that the proposed tutorial is not adding new ideas and therefore I'd close this. If you have other ideas, please fee free to create a new issue and elaborate on the overview.
