### ISSUE TITLE
Bug - the Digital Ocean guide has broken pics

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb.io#1200]
https://questdb.io/docs/deployment/digitalocean/
shows broken images:
<img width="871" alt="image" src="https://user-images.githubusercontent.com/158619/203269572-7a2027ab-296b-4ebb-a128-8678448779ed.png">

<img width="838" alt="image" src="https://user-images.githubusercontent.com/158619/203269695-1e7c2beb-751b-4748-85ac-1eb929e78f65.png">

I'd imagine there are bots you can configure to crawl your website and notify you when they find a broken link/image. Perhaps we could try to use it.

**Comment by pswu11** [comment]
I think we have some setup to detect broken links with Netlify, not sure how this one escaped.

**Comment by jerrinot** [comment]
maybe Netlify just checks actual links (`<a href="...">`) while this one is an image? (`<img src="...">`)?
