### ISSUE TITLE
Cloud documentation

### ISSUE THREAD

**Issue by amyshwang** [questdb/questdb.io#1220]
Investigate the requirement for QuestDB Cloud

**Comment by saikrishnatbijil** [comment]
@amyshwang can you explain a bit more on what to do

**Comment by professorabhay** [comment]
Hai @amyshwang, I am interested to work on this.
Please assign it to me. 
I'll resolve it asap!! 🙂

**Comment by amyshwang** [comment]
Hey @professorabhay and @saikrishnatbijil, this is about our Cloud service, which is not open-source. I shall close the issue as this is just a note for the team.
