### ISSUE TITLE
Update - red panda integration

### ISSUE THREAD

**Issue by amyshwang** [questdb/questdb.io#1387]
**Describe the requested changes:**

Red panda integration page

Some thoughts about the page structure:

- What is Redpanda
- An example replacing a Kafka connector with redpanda - maybe using [the example of our kafka connector](https://github.com/questdb/kafka-questdb-connector/blob/main/kafka-questdb-connector-samples/stocks/docker-compose.yml)
- reference: https://docs.redpanda.com/docs/get-started/quick-start/quick-start-docker/
Question: is this possible to do at all?
- See also links
  - We can elaborate this idea into a separate blog post:
```
How to import Parquet files to QuestDB.
QuestDB does not support Parquet files directly, but I think it should be possible to import them via the Pandas support. As Parquet files can be transformed to Pandas (I think I saw it in one of the Adam’s examples). I think that’s currently the most efficient way to load Parquet files to QuestDB
```
I think the parquet example is better suited as a tutorial as using redpanda is not necessarily the best way of doing it; it's one of many methods.

**Comment by jerrinot** [comment]
ad Parquet: sorry, I was not clear enough. the Parquet idea is unrelated to Redpanda. It was meant to be an example of another possible integration. Arguably more valuable - as we already have Kafka documentation and the Redpanda blog. but we do not have anything sensible about importing Parquet files. 

"How to use QuestDB Kafka Connector with Redpanda" and the proposed outline sounds interesting.

**Comment by amyshwang** [comment]
Okay - parking the task for importing parquet file as this is another WIP.
Focusing on redpanda, you previously mentioned:

> 
> If we do a Redpanda tutorial then we should probably split this page: https://questdb.io/docs/third-party-tools/kafka/questdb-kafka/
> The page is currently both a reference manual for the connector and also a tutorial showing how to use the connector with Apache Kafka. For Redpanda you would use the same connector.
> 
> QuestDB Connector reference manual
> Tutorial showing how to use the connector with Apache Kafka
> Tutorial showing how to use the connector with Redpanda

This feels better than replacing part of an existing docker compose file.

Currently we have:
<img width="297" alt="Screenshot 2023-02-10 at 13 57 16" src="https://user-images.githubusercontent.com/107401731/218014080-a32c4432-3c1f-431f-95af-fe755b8f617d.png">

If I understand this correctly, I think we want to following the flow of [this page](https://questdb.io/docs/third-party-tools/kafka/questdb-kafka/) and create one for redpanda.

In order not to disturb the existing pages, I think we could try:

Kafka
  > Overview
  > -QuestDB Kafka Connector-
 > JDBC connector

**Comment by amyshwang** [comment]
Redpanda does not have its own framework for running connectors. They rely on Kafka Connect. So when you want to run Redpanda with QuestDB you have to:

1. Download Redpanda
2. Download Apache Kafka. Why? Kafka Connect is part of Apache Kafka distribution.
3. At this point you have both Redpanda and Apache Kafka on your local :upside_down_face:
4. Download QuestDB
5. Start Redpanda
6. Start QuestDB
7. Add QuestDB Connector JAR to Kafka Connect
8. Start Kafka Connect
9. Use curl to configure & start QuestDB Connect running inside Kafka Connect. This is exactly the same as with our Kafka tutorial.

It looks complicated, but it really is not. It’s very very close to https://questdb.io/docs/third-party-tools/kafka/questdb-kafka/
The only differences are:

- you have one extra download: Redpanda itself
- replace the steps “Start the Kafka Zookeeper” and “Start a Kafka server” with “Start Redpanda”. The step “Start the QuestDB Kafka connector” remains.

**Comment by amyshwang** [comment]
From @jerrinot:

This Redpanda -> QuestDB tutorial is based on the Apache Kafka -> QuestDB tutorial at: https://questdb.io/docs/third-party-tools/kafka/questdb-kafka/
Prerequisites: 
1. Docker + access to internet to download Redpanda container image
2. A running QuestDB instance

There is one big difference compared to the Apache Kafka tutorial: We will be running Redpanda inside Docker, because apparently Redpanda is running on Linux only and containers will ensure that - even when your host machine is MacOS or Windows. 


Steps:
1. Create docker-compose.yml with [this content](https://docs.redpanda.com/docs/get-started/quick-start/quick-start-docker/):
[...]

save the file and run `docker compose up`. This will start a single Redpanda broker inside Docker and will also expose Redpanda to your host machine. 
It also start Redpanda web console (which is quite nice to use)

2. Download Apache Kafka - https://downloads.apache.org/kafka/3.4.0/kafka_2.12-3.4.0.tgz
Q: Wait! Why do we need need Apache Kafka for? This is a Redpanda tutorial, isn't it?
A: Well, Redpanda does not have Kafka Connect equivalent - it piggy backs on Kafka Connect from Apache Kafka distribution. So we download the Apache Kafka distribution for the sake of Kafka Connect. We could also use a Docker, but I feel it would be less transparent for readers. 

Unzip kafka. 

3. Download QuestDB connector: https://github.com/questdb/kafka-questdb-connector/releases/download/v0.5/kafka-questdb-connector-0.5-bin.zip
Unzip the connector - it has a directory with 2 JARs: Copy these JARs into /path/to/kafka/lib There should be already a lot of other JAR files. That's how you can tell you are in the right directory.

4. Go to /path/to/kafka/confing - there should be already quite a few *.property files. Create a new file: questdb-connector.properties with this:
name=questdb-sink
connector.class=io.questdb.kafka.QuestDBSinkConnector
host=localhost:9009
topics=example-topic
table=example_table
include.key=false
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
key.converter=org.apache.kafka.connect.storage.StringConverter

5. cd /path/to/kafka and execute: ./bin/connect-standalone.sh config/connect-standalone.properties config/questdb-connector.properties
This starts Kafka Connect

6. Go to http://127.0.0.1:8080/topics - This is Redpanda web console. It should display example-topic. If the topic is not there then refresh a few times.
Click at Action-Public message and paste this:
{"firstname": "Arthur", "lastname": "Dent", "age": 42}

7. Go to QuestDB console: http://localhost:9000/
run: select * from example_table;
you should see the message. 

8. Celebrate! :)
