### ISSUE TITLE
Add guidelines for Capacity Planning

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb.io#146]
__Overview:__

We need to document features such as:

- CPU configuration
- Storage configuration
- OS configuration with respect to limits, such as max open files
- In linux check user and system max open files (ulimit -Sn, ulimit -Hn and sysctl fs.file-nr)
- In linux check max mapped files sysctl (vm.max_map_count)

Default page size for writers. This value is 16Mb. There have been cases where customers have large number of small tables. In this case using 16MB page to write 1MB of data max is wasting OS resources. It is possible to change default value via config file. This value is rounded (ceiling) to the multiple of OS page sizes:

```
cairo.sql.append.page.size
```

## CPU configuration

We need to describe how to configure system to prioritize ingestion over query and other way around. We have various worker pools, which can help separate CPU load between sub-systems. E.g. ingestion can has its own threads and CPU core affinity, separate from query system

## Storage configuration

Help users calculate storage requirements for particular table structure

## Edge cases

Extend OS limits, such as max open files, max mapped files etc

**Comment by bluestreak01** [comment]
## cpu configuration

we need to describe how to configure system to prioritise ingestion over query and other way around. We have various worker pools, which can help separate CPU load between sub-systems. E.g. ingestion can has its own threads and CPU core affinity, separate from query system

**Comment by bluestreak01** [comment]
## storage configuration

help users calculate storage requirements for particular table structure

**Comment by bluestreak01** [comment]
## edge cases

extend OS limits, such as max open files, max mapped files etc

**Comment by bsmth** [comment]
PR for this open at #364
