### ISSUE TITLE
Document ILP authentication

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb.io#150]
We need to document supported authentication methods and how to configure them with examples.

**Comment by patrickSpaceSurfer** [comment]
ILP over TCP client authentication

This works by using an elliptic curve P-256 JSON web token (JWT) to sign a server challenge.
The server is configured by adding an authentication db file, such as the example one at:
https://github.com/questdb/questdb/blob/master/core/src/test/resources/io/questdb/cutlass/line/tcp/authDb.txt
The server.conf needs to be configured to enable ILP over TCP client authentication by adding the 
line.tcp.auth.db.path setting which points the the  authentication db file, such as:
line.tcp.auth.db.path=conf/authDb.txt
The format of the file is documented in the example file, which also contains an example JWT.
The client needs to generate their own web tokens, below is a jfiddle with an example on how to do it in javascript:
https://jsfiddle.net/patrick73/3uhkyqz6/latest/
The following website can also be used:
https://mkjwk.org/

Once its setup the server expects the client to send its key id (terminated with \n) straighn after connect
The server will respond with a challenge (printable characters terminated with \n)
The client needs to sign the challenge and respond to the server with the base64 encoded signature (terminated with \n)
If all is good the client can then continue sending normal ILP, if not the server will disconnect and log the failure

To test ILP auth I suggest you copy the
https://github.com/questdb/questdb/blob/master/core/src/test/resources/io/questdb/cutlass/line/tcp/authDb.txt
file to the conf/ directory and add the following line to your server.conf
line.tcp.auth.db.path=conf/authDb.txt
You can then test using the jwt in the authDb.txt file

**Comment by mpsq** [comment]
Done
