### ISSUE TITLE
Configuration properties can be overriden with environment variables

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb.io#151]
All of the values from `server.conf` can be superseded by corresponding environment variables. The goal is to enable easy change of QuestDB configuration values in containerized deployments.

The conversion rule from property name into to environment variable is expressed like this:

```java
String envCandidate = "QDB_" + key.replace('.', '_').toUpperCase()
```

for example to override configuration key

```
cairo.sql.float.cast.scale
```

one would have to declare environment variable

```
QDB_CAIRO_SQL_FLOAT_CAST_SCALE
```

It might be useful to reference this information from the capacity planning guide #146

**Comment by mpsq** [comment]
Done in #155
