### ISSUE TITLE
New examples needed

### ISSUE THREAD

**Issue by mpsq** [questdb/questdb.io#152]
# TODO

## REST API

QUERY data, examples needed for:

- [x] cURL (@mpsq)
- [x] NodeJS (@mpsq)
- [x] Go (@mpsq)
- [ ] Java (@bluestreak01)

INSERT data, examples needed for (done with `/query`):

- [x] cURL (@mpsq)
- [x] NodeJS (@mpsq)
- [x] Go (@mpsq)
- [ ] Java (@bluestreak01)

INSERT data, examples needed for (done with `/imp`):

- [x] cURL (@mpsq)
- [x] NodeJS (@mpsq)
- [x] Go (@mpsq)
- [ ] Java (@bluestreak01)

## ILP (TCP)

INSERT data, examples needed for:

- [x] NodeJS (@mpsq)
- [x] Go (@mpsq)
- [x] Java (@bluestreak01)

## Postgres

QUERY data, examples needed for:

- [x] NodeJS (@mpsq)
- [x] Go (@mpsq)
- [x] Java (@bluestreak01)

INSERT data, examples needed for:

- [x] NodeJS (@jaugsburger)
- [x] Go (@jaugsburger)
- [x] Java (@bluestreak01)

# In the future

Support for other languages:

- Python
- C#
- Rust

**Comment by mpsq** [comment]
@bluestreak01 I added you on the Java examples.

**Comment by mpsq** [comment]
@jaugsburger I added you on the NodeJS / Go examples for **insert** on Postgres.

**Comment by bsmth** [comment]
There is related work ongoing in https://github.com/questdb/questdb.io/pull/308

**Comment by filipsPL** [comment]
An example of inserting data using ILP (TCP) and netcat and command line in linux/bash/command line:

`echo "trades,name=ilp_stream_73 value=12.4" | nc -q 1  localhost 9009`
