### ISSUE TITLE
Configure log from Env

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb.io#160]
Log is usually configures from file. Here is example of such file:

```
# list of configured writers
writers=file,stdout

# file writer
#w.file.class=io.questdb.log.LogFileWriter
#w.file.location=questdb-debug.log
#w.file.level=INFO,ERROR

# stdout
w.stdout.class=io.questdb.log.LogConsoleWriter
w.stdout.level=INFO,ERROR
```

QuestDB will look for `/qlog.conf` on classpath unless this name is overridden via "system" property `-DquestdbLog=/something_else.conf`

When loading the properties file QuestDB will be looking for Env overrides using suffix `QDB_LOG_`. For example `w.stdout.level` can be overridden via env variable:

```
QDB_LOG_W_STDOUT_LEVEL=ERROR
```

QuestDB logging can be quickly forced globally to Debug via either providing java option `-Debug` or setting env variable `QDB_DEBUG=true`

Note that `-Debug` relies on Java system property "ebug" to be set. -D is handled by java and therefore this option must be before java main class on the command line.

**Comment by mpsq** [comment]
Done
