### ISSUE TITLE
Table join without explicit JOIN clause, via ','

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb.io#161]
PostgreSQL metadata queries sometimes join tables using the following syntax:

```sql
select * from a,  b where a.id = b.id
```

in this case optimiser would have to infer join criteria from the `where` clause and effectively make this SQL equivalent to:

```sql
select * from a join b on (id)
```

QuestDB parser and optimiser now do do that. Type of join is entirely inferred from the where clause and may end up being either `INNER` join or `CROSS` join. There is no way to use former syntax to create any other type of join because there is not enough information on the where clause.

That said Oracle supports `where a = b(+)` for `OUTER` join. QuestDB does not yet support this.

**Comment by mpsq** [comment]
Done
