### ISSUE TITLE
Update - document how to JOIN on multiple columns

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb.io#1623]
The [JOIN reference page](https://questdb.io/docs/reference/sql/join/) does not show good examples how to join tables on multiple columns. All examples use a join on a single column only and only the grammar graphs suggest we can do join on multiple columns

<img width="836" alt="image" src="https://user-images.githubusercontent.com/158619/234596928-e6e5de96-3073-4834-9c5b-c14ab5972f3e.png">

The documentation should be more explicit about this and add examples.

**Comment by professorabhay** [comment]
Hai @jerrinot, I am interested to work on this issue.
Please assign it to me.

**Comment by amyshwang** [comment]
@professorabhay there is already a PR linking to it.
