### ISSUE TITLE
Update - <DocspageTabs>

### ISSUE THREAD

**Issue by amusoni240** [questdb/questdb.io#1797]
![Screenshot (32)](https://github.com/questdb/questdb.io/assets/139322377/fdffb946-4446-45fc-baac-0c0e8964f069)

-->here in the right after the reference tab all the tabs have spacebefore them ,it effect the UI and look awkward fix it

the tabs have spacebefore them ,it effect the UI and look awkward fix it

**Comment by insmac** [comment]
This is intentional, as these items are logically under _Reference_ and the UI follows a tree-like visual pattern.
