### ISSUE TITLE
Remove / update error codes from REST api reference documentation

### ISSUE THREAD

**Issue by mpsq** [questdb/questdb.io#194]
Since [this change](https://github.com/questdb/questdb/pull/684), the REST api does not send errors with a status code set to `400`.

Instead, the API answers with successful responses (status set to `200`). The body of the response is the following

1. When the request has a `query` (`/exp` and `/exec`):

```json
{
  "error": "Error message",
  "position": 7,
  "query": "SELECTT * FROM table;"
}
```

Where the `position` is a number that indicates which character in the query string causes the error.

2. Without a `query` (`/imp` endpoint):

```json
{
  "error": "Error message"
}
```

The [corresponding documentation](https://questdb.io/docs/reference/api/rest#error-response) needs to be updated to reflect that change.

**Comment by bsmth** [comment]
fixed in #250
