### ISSUE TITLE
Adding new keywords (per page):

### ISSUE THREAD

**Issue by prtkgpt** [questdb/questdb.io#266]
## /blog/memory-mapping-deep-dive
- performance
- deep-dive
- questdb
- database
- tutorial

## /blog/line-protocol
- influxdb
- questdb
- ILP

## /blog/my-journey-writing-questdb
- hackernews
- story
- startup
- founder
- cto
- timeseries
- database
- ycombinator

## /blog/influxdb-lp-on-tcp
- influxdb line protocol
- timeseries
- databases
- questdb
- TCP
- ILP

## /blog/we-put-a-sql-database-on-the-internet
- hackernews
- postmortem
- sql database
- timeseries database
- questdb

## /blog/python-questdb-tutorial
- python
- docker
- jupyter notebook
- questdb
- databases
- timeseries
- tutorial

## /blog/iot-on-questdb
- iot
- databases
- questdb
- timeseries
- DHT11 sensor
- Ardrino

## /blog/interesting-things-we-learned-about-sums
- performance
- benchmarking
- deep-dive
- kahan
- neumaier
- databases
- SIMD
- clickhouse

## /blog/use-questdb-for-swag
- projects
- community
- questdb
- swag

## /blog/interthread
- deep-dive
- inter-thread messaging
- questdb
- database
- infrastructure

## /blog/using-simd-to-aggregate-billions-of-rows-per-second
- performance
- simd
- parallelization
- CPU
- QuestDB

**Comment by mpsq** [comment]
Done
