### ISSUE TITLE
Issues in Footer of Web Site

### ISSUE THREAD

**Issue by sirinath** [questdb/questdb.io#30]
1. Under community, the twitter links it does not point to twitter handler: https://twitter.com/QuestDB but it just points to https://twitter.com/
2. Roadmap points to the current sprint which I belive is: https://github.com/questdb/questdb/projects/2 but the road map is on https://github.com/questdb/questdb/projects/3

![image](https://user-images.githubusercontent.com/637415/82682161-7154b800-9c6c-11ea-8e55-ae7a16cb7ba1.png)

**Comment by davidgs** [comment]
1) is fixed with https://github.com/questdb/questdb.io/commit/21d83912eacc8083edc8b7bd553569e6f1b7e068
