### ISSUE TITLE
Add documentation for column rename

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb.io#375]
Document the following:

```sql
alter table TAB rename column X to Y
```

Tests for column rename SQL can be found here:

https://github.com/questdb/questdb/blob/master/core/src/test/java/io/questdb/griffin/AlterTableRenameColumnTest.java

Column names are validated not to contain special characters. Validation logic is here:

https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/griffin/SqlKeywords.java#L705

**Comment by bsmth** [comment]
added in #376
