### ISSUE TITLE
Bug - outdated docusaurus configs cached on re-build

### ISSUE THREAD

**Issue by bsmth** [questdb/questdb.io#493]
**Bug description:**
A documentation page which uses string substitution during build time has an older QuestDB software version number in the Netlify deploy than is stated in docusaurus.config.

The version number is set in https://github.com/questdb/questdb.io/blob/master/docusaurus.config.js#L24

use of this var: https://github.com/questdb/questdb.io/blame/master/docs/get-started/binaries.md#L27

Location of this outdated var in deployed HTML: https://questdb.io/docs/get-started/binaries

**Additional Context:**
Persisted caching as of webpack 5 means that builds are cached for faster rebuild times. It seems when there are no filesystem changes detected for the source page, and an older version of this page is used instead.

**Comment by bsmth** [comment]
@slorber have you seen this behavior before or are there any hints for clean builds on Netlify?

**Comment by slorber** [comment]
We now use Webpack 5 with persistent caching, it's possible that the cache kicks in while it shouldn't and return cache hits using the older version.

Try using `docusaurus clear`

I think we should use this option to make sure the cache is evicted whenever you touch the docusaurus config file.

https://webpack.js.org/configuration/other-options/#cachebuilddependencies

**Comment by bsmth** [comment]
Thanks for the hint, I will give `yarn docusaurus clear` a shot. At the moment, the workaround for us is to touch the source file so filesystem changes get picked up.

> the cache is evicted whenever you touch the docusaurus config file

That could be a good idea, it would solve the unexpected behavior here, at least 👍🏻

**Comment by slorber** [comment]
Will be solved by https://github.com/facebook/docusaurus/pull/5047

**Comment by slorber** [comment]
Please test if it works better for you with the canary release:
https://docusaurus.io/community/canary

**Comment by bsmth** [comment]
Thanks a lot, Sébastien, I will give it a spin.

**Comment by bsmth** [comment]
@slorber I'm bumping to `2.0.0-beta.4` in https://github.com/questdb/questdb.io/pull/520 to fix this issue, but I'm hitting breaking changes.

I seem remember reading in the Docusaurus release notes that `ConfigureWebpackUtils` needs newer handling, but I'm lost on the necessary changes.

---

Error thrown in https://github.com/questdb/questdb.io/blob/b_docusaurus_beta/plugins/tutorial/index.ts#L173 (`plugins/tutorial/index.ts`)

CI for reference - https://github.com/questdb/questdb.io/pull/520/checks?check_run_id=3251246326
Relevant log output:

```bash
plugins/tutorial/index.ts(173,5): error TS2322: Type '(_config: Configuration, isServer: boolean, { getJSLoader }: ConfigureWebpackUtils) => { resolve: { alias: { "~tutorial": string; }; }; module: { rules: { test: RegExp; include: string[]; use: RuleSetRule[]; }[]; }; }' is not assignable to type '(config: Configuration, isServer: boolean, utils: ConfigureWebpackUtils, content: TutorialContent) => Configuration & { ...; }'.
  Types of parameters '_config' and 'config' are incompatible.
    Type 'import("/home/runner/work/questdb.io/questdb.io/node_modules/@docusaurus/types/node_modules/webpack/types").Configuration' is not assignable to type 'import("/home/runner/work/questdb.io/questdb.io/node_modules/webpack/types").Configuration'.
      Types of property 'entry' are incompatible.
        Type 'string | string[] | import("/home/runner/work/questdb.io/questdb.io/node_modules/@docusaurus/types/node_modules/webpack/types").EntryObject | (() => string | string[] | import("/home/runner/work/questdb.io/questdb.io/node_modules/@docusaurus/types/node_modules/webpack/types").EntryObject | Promise<...>)' is not assignable to type 'string | string[] | import("/home/runner/work/questdb.io/questdb.io/node_modules/webpack/types").EntryObject | (() => string | string[] | import("/home/runner/work/questdb.io/questdb.io/node_modules/webpack/types").EntryObject | Promise<...>)'.
          Type 'EntryObject' is not assignable to type 'string | string[] | EntryObject | (() => string | string[] | EntryObject | Promise<EntryStatic>)'.
            Type 'EntryObject' is not assignable to type 'string'.
            
```

**Comment by slorber** [comment]
Hey,

Both types should be compatible. I think the problem may be because you have 2 distinct versions of Webpack locally due to Yarn not de-duplicating correctly?
- questdb.io/node_modules/@docusaurus/types/node_modules/webpack/types
- questdb.io/node_modules/webpack/types

If those 2 versions are not compatible with each other it might lead to weird issues?

**Comment by bsmth** [comment]
closing for the moment
