### ISSUE TITLE
Spaces need to be escaped for using line protocol

### ISSUE THREAD

**Issue by spxie85** [questdb/questdb.io#502]
https://questdb.io/docs/guides/influxdb-line-protocol/ mentions that "spaces and commas do not require an escaping backslash in the field value for string".  This is incorrect for spaces. They _DO_ need to be escaped.

If suppose you run below code without escaping the space in "sample_string", you'll end up with an error that says something like:
`2021-07-02T04:34:18.669039Z E i.q.c.l.t.LineTcpConnectionContext [1276] could not parse measurement, code INVALID_FIELD_VALUE at 27 line (may be mangled due to partial parsing) is table_a indexName="INDEX A"`

The issue is resolved once you escape space with a \

```python
import socket

class QuestDBClient():
    
    def __init__(self, host='localhost', port=9009):

        self.host = host
        self.port = port
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)     

    def sendall(self, lines):
        self.sock.connect((self.host, self.port))                  
        self.sock.sendall(''.join(lines).encode())       
        self.sock.close()  

if __name__ == '__main__':
    sample_string = ['table_a indexName="INDEX A"\n']

    client = QuestDBClient()
    client.sendall(sample_string)

```

**Comment by bsmth** [comment]
Thanks for opening the issue @spxie85 , I tried out the example and it's indeed not working, however the comma after the table name is required, i.e., the following will work:

```python
    # without symbols (Tags)
    sample_string = ['table_a, indexName="INDEX A"\n']
    sample_string = ['table_a, string="with space"\n']
    # with a symbol value
    sample_string = ['table_a,sym=symbol string="with space"\n']
```

What does break is if whitespace in symbol types are not escaped:

```python
    sample_string = ['table_a,sym="symbol unescaped" string="nospaces"\n']
```

working equivalent:

```python
    sample_string = ['table_a,sym="symbol\ escaped" string="nospaces"\n']
```

**Comment by spxie85** [comment]
thanks for the clarification. I wonder if the intent was for ILP to avoid escaping spaces and commas (preferred), or whether this was purely a documentation error?
