### ISSUE TITLE
Error following "Create my first database"

### ISSUE THREAD

**Issue by mingodad** [questdb/questdb.io#524]
**Describe the bug**
Following the "Create my first database" and on this query:
```
{"query":"SELECT ts, city, make, avg(temp)\nFROM readings timestamp(ts)\nJOIN\n    (SELECT ID sensId, city, make\n    FROM sensors\n    WHERE city='Miami' AND make='Omron') a\nON readings.sensorId = a.sensId\nWHERE ts ='2019-10-21;1d' -- this is an interval between 21-10 and 1 day later","error":"Not a date, use IN keyword with intervals","position":202}
```

**Environment (please complete the following information):**
 - OS: Linux, Ubutntu 18.04
 - Browser: chromium
 - Build Information: QuestDB 6.0.4, JDK 11.0.10, Commit Hash 2d16df8f0846707f34f76f96864e93f0cafe85f3

**Additional context**
It seems that something changed but the documentation doesn't, meaning that the documentation examples are not tested on each release.

**Comment by mingodad** [comment]
Thanks for reply !
I still think that having the messages/notifications permanently (maybe in a `TAB` the last X messages/notifications) is a better option.

**Comment by mingodad** [comment]
Maybe another `TAB` on the same row as `Grid`, `Chart`, `Notifications or Logs`.

**Comment by bsmth** [comment]
No problem, that's a good idea. You can request this feature in the discussions section of the QuestDB repository -> https://github.com/questdb/questdb/discussions/categories/ideas I'm sure others will find this helpful 🙌🏻

**Comment by mingodad** [comment]
And if there is an error the corresponding `TAB` is activated showing the message.

**Comment by mingodad** [comment]
Also there is no mention about the username/password when connecting with `psql` and after searching the issues https://github.com/questdb/questdb/issues/782 I found it's admin/questdb
