### ISSUE TITLE
Inconsistent CSS styles when code block extends greater than page width

### ISSUE THREAD

**Issue by akshitarora921** [questdb/questdb.io#568]
**Bug description:**
The page style is inconsistent, for some pages sidebar shifts outside the screen

**Location:**
- https://questdb.io/docs/operations/backup
- https://questdb.io/docs/third-party-tools/kafka

**Screenshots:**
![image](https://user-images.githubusercontent.com/11087313/136465863-4777c905-5fee-4c1f-b2ff-97dcbb472c23.png)
![image](https://user-images.githubusercontent.com/11087313/136466123-ce5e7052-9ea2-4dd1-9fe6-7b6c3ba33e24.png)

**Browser and OS:**
Chrome Version 94.0.4606.71
Ubuntu 21.04

**Comment by argshook** [comment]
Hello! It's me, from future! Since this issue was opened a lot of website code was updated which included a fix for this issue.

Thus, considering as fixed, closing.

Please feel free to open another issue if it still persists on some page. Thank you!
