### ISSUE TITLE
website: add newsletter subscription bar to website's footer 

### ISSUE THREAD

**Issue by pswu11** [questdb/questdb.io#590]
It'd be nice if we can make the newsletter's subscription more obvious. 
At the moment, you can only find it on the swag page, the flow is not very straightforward. 
If it's on the footer (or landing page) then potential users can see it very easily. 

Examples from other websites that have this component in the footer:

![Screenshot from 2021-10-27 16-15-39](https://user-images.githubusercontent.com/48913707/139083881-496b9316-a7bb-4899-9b61-bcd281eba000.png)
![Screenshot from 2021-10-27 16-18-01](https://user-images.githubusercontent.com/48913707/139084209-b015586e-1e94-4075-a5c2-d9edf4483e7d.png)

**Comment by prajalsharma** [comment]
Hey can you assign this to me , I can do a html, css magic to make it work ???
