### ISSUE TITLE
Adding Data to QuestDB

### ISSUE THREAD

**Issue by AnkitArsh19** [questdb/questdb.io#640]
## My tutorial idea

> I would like to write a tutorial that shows how to add 500 entries of data to our database.

import requests
import random
from datetime import datetime
success = 0
fail = 0
random.seed()
for x in range(500):
    temp = random.randint(-40, 55)
    rain24H = round(random.uniform(10.45, 235.15), 2)
    thunder = bool(random.getrandbits(1))
    query = "insert into weather values("\
        + str(temp) + ","\
        + str(rain24H) + "," \
        + str(thunder) +",systimestamp())"
    r = requests.get("http://localhost:9000/exec?query=" + query)
    if r.status_code == 200:
        success += 1
    else:
        fail += 1
    
print("Rows inserted: " + str(success))
if fail > 0:
    print("Rows Failed: " + str(fail))
Output: Rows inserted: 500

💡 ...

## Community vote

Please leave your feedback on this tutorial

👍 I need this! 🚀 I can help you!

**Comment by bsmth** [comment]
Hi @AnkitArsh19 thanks for the suggestion. I'm going to close this one for the moment as we are looking for more in-depth tutorials. To get an idea of what we're looking for, see https://github.com/questdb/questdb.io/blob/master/tutorial/2021-11-01-plotly-finnhub-realtime-dashboard.mdx

Thank you! :)
