### ISSUE TITLE
type definition - doc vs implementation

### ISSUE THREAD

**Issue by robocoder** [questdb/questdb.io#644]
**Describe the bug**
On https://questdb.io/docs/reference/sql/create-table#indexdef, the options for the `symbol` type show CACHE and NOCACHE as independent of the capacity option.  QDB 6.0.4 insists that capacity is expected. 

**To Reproduce**
```sql
CREATE TABLE tracking (
        ts       TIMESTAMP,
        id       SYMBOL INDEX NOCACHE,
        location SYMBOL,
        status   SYMBOL,
        scanby   SYMBOL
    )
    timestamp(ts)
    PARTITION BY DAY;
```
Error:
```
psql:ddl.sql:10: ERROR:  'capacity' expected
LINE 3:         id       SYMBOL INDEX NOCACHE,
```

**Expected behavior**
Either correct the documentation, or change the implementation.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu 20.04)
 - Browser: Chrome 92.0.4515.159 (Official Build) (x86_64)
 - Version: 6.0.4-rt-linux-amd64

**Additional context**
- postgresql-client-12

**Comment by bsmth** [comment]
Thanks for opening this one, I'll update the diagram to show that `cache` / `nocache` must be preceded by symbol capacity for the moment
