### ISSUE TITLE
announcement visual artifact 

### ISSUE THREAD

**Issue by popuguytheparrot** [questdb/questdb.io#79]
Hi guys. I checking showcases and looked at yours and find bug.
![image](https://user-images.githubusercontent.com/19804652/89103071-d02a7080-d417-11ea-8854-13b97e693033.png)
When disabled height styles
![image](https://user-images.githubusercontent.com/19804652/89103149-4f1fa900-d418-11ea-9e3c-536d5f21301b.png)
Looks better
![image](https://user-images.githubusercontent.com/19804652/89103155-5f378880-d418-11ea-9fff-255b7da52eb9.png)

**Comment by mpsq** [comment]
Thanks @popuguytheparrot for reporting this, I will have a look.

**Comment by mpsq** [comment]
I had a look and I am not able to reproduce this issue, can you provide:

- browser used (with version)
- viewport dimensions (your screenshot indicates that you are using DevTools with the responsive mode on?)
- how to reproduce the bug

Thank you

**Comment by popuguytheparrot** [comment]
@mpsq 
* Chrome 84
* Mobile L
* Open devtools. Set Mobile L viewport. Dont close announcement and scroll down

**Comment by mpsq** [comment]
Following your instructions, I am not able to reproduce the issue, is there a something I am missing?

My test:

![ezgif-7-482fb69eeae9](https://user-images.githubusercontent.com/5734722/89306216-74eebd00-d667-11ea-8aaf-5b11b594b73d.gif)

**Comment by popuguytheparrot** [comment]
It strange... Even in incognito mode, but from real mobile device look good. Okey... Close issue. Sorry for it

**Comment by mpsq** [comment]
No worries! Thanks for taking the time to debug this!
