### ISSUE TITLE
Bug - incorrect timestamp filter description

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb.io#857]
![image](https://user-images.githubusercontent.com/7276403/169871891-cc170105-8deb-45c1-bb4d-1225ab5420c9.png)

On this screenshot the original upper bound is `Jan` not `Dec`.

**Comment by amyshwang** [comment]
The date in the table - 2019-01-28 should also be changed to 2018-01-28? I checked the source and it might be a simple copy paste error from the table above?
