### ISSUE TITLE
Simplify - Get started with QuestDB from the binaries

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb.io#862]
**Describe the requested changes:**
1. This [page](https://questdb.io/docs/get-started/binaries/) could be simplified. The most impactful change: Do not start with the "Any (No JVM)" version. It forces us to bother users with the Java version, JAVA_HOME env. variable, etc. That's scary, especially for non-Java folks. If we start with the OS-specific versions and leave the "No JVM" version in some "for experts" sections it will simplify the flow quite a bit. 

2. Confirm the commands used on this page to be correct
3. "Next steps" points to the command-line page, so it should probably be moved to before "Upgrade QuestDB version"; Upgrade QuestDB version section level needs to be moved up.

Alternatively, we could merge various installation methods into a single page. This looks nice: - 
https://materialize.com/docs/get-started/ (thanks to @pswu11 for the idea)
https://go.dev/doc/install

**Location:**
https://questdb.io/docs/get-started/binaries/

<img width="858" alt="image" src="https://user-images.githubusercontent.com/158619/170694686-84c98a30-70cc-4a6a-89bd-3864486960d3.png">

**Comment by Rutam21** [comment]
@amyshwang I would love to update the documentation. Please assign this to me and add the `hacktoberfest` label to this as well. Thanks.

**Comment by amyshwang** [comment]
@Rutam21 Assigned to you but I also added more to the task as I noted more problems.

**Comment by amyshwang** [comment]
Page already updated thanks to other improvement tasks. Closing the issue.
