### ISSUE TITLE
(docs) investigate ways to reuse terms using metadata

### ISSUE THREAD

**Issue by amyshwang** [questdb/questdb.io#900]
In `lexicon.md`, there are conventions for specific terms for the Docs (or event the whole website) to follow.
To ensure consistency, it may be useful to investigate ways to automate this.

E.g.  a yaml file defining the terms and abbreviations. Each md source then call the term by using specific syntax (@abbr, for instance). A script could perhaps auto populate the full terms.

I am not sure if this is possible with Docusaurus but some similar mechanism could reduce maintenance burdens significantly.

To-do:
1. Understand how metadata for the website is set.
2. Investigate whether terms could be defined and reuse by the tool
3. Compile/expand lexicon list
4. Implement if this is feasible

**Comment by argshook** [comment]
Since the genesis of this issue we have implemented a semi-automated glossary page: questdb.io/glossary

thus, closing the ticket.
