### ISSUE TITLE
Bug - non-existing link for Web Console's Assets Path

### ISSUE THREAD

**Issue by shantanoo-desai** [questdb/questdb.io#902]
**Bug description:** The link mentioned for an example `.env` file for updated assets for WebConsole points to a non-existing GitHub Link

**Location:** https://questdb.io/docs/develop/web-console/#providing-an-asset-path

**Screenshots:**
![QuestDBDocsBug](https://user-images.githubusercontent.com/12070966/174311082-97d59f53-2486-4950-a4cf-0e701eda3399.gif)

**Browser and OS:**
__Google Chrome__: `102.0.5005.115 (Official Build) (64-bit)`
__Windows 10__

### Further Info

Since `ui` is now it's own repository I am not sure if the `.env` file exists or not or whether it is still relevant

**Comment by argshook** [comment]
Hey @shantanoo-desai, thank you for pointing this out!

Indeed the link directed to a wrong location. The link has been fixed.

Cheers!
