### ISSUE TITLE
chore (docs) Enhancement: client libs pages

### ISSUE THREAD

**Issue by amyshwang** [questdb/questdb.io#923]
Currently we have one landing page for client libraries, with links to each GH.
This is not a lot of content.

Think about fleshing out this page into a section, with each language having their own sub-page.
Each language can have sample code and rationale.

Challenge: 
* Avoid duplicating content in readme in GH: may need to migrate content form github readme to the website.
* Ideally each subpage should have a similar structure.
* https://questdb.io/docs/develop/insert-data spends a lot of space discussing internals of ILP. see the sections ILP Datatypes and Casts[#](https://questdb.io/docs/develop/insert-data/#ilp-datatypes-and-casts) or Constructing well-formed messages[#](https://questdb.io/docs/develop/insert-data/#constructing-well-formed-messages)
that was needed when clients didn’t not existed. but that’s not the case anymore. most users should not have to deal with details of the protocol anymore. clients will do it for them. so perhaps we could move this to reference/for-experts part of the docs? (stole from @jerrinot )

**Comment by jerrinot** [comment]
Good point about content duplication. I believe GH readme should have info for client developers & contributors. Info how to contribute to the client, how to run tests, coding standards, etc. 

User-centric documentation (=how to use it) for all clients should in at questdb.io/docs. 

@puzpuzpuz @amunra @ideoma: as client maintainers - does ☝️ make sense to you?

**Comment by amunra** [comment]
Overall yes, but within the constraints of being able to understand what is written on the page without too much jumping around a small amount of repetition is fine IMO. 

Specifically, there should be no assumption that a user will start reading the related questdb docs before a client's docs.

There's certainly areas of the C client docs that ought to be moved. As an example, I would welcome a page that I can refer to for TLS that explains haproxy conceptually and generating certs. I lieu of that I currently have this page: https://github.com/questdb/c-questdb-client/blob/main/tls_certs/README.md.

**Comment by puzpuzpuz** [comment]
> User-centric documentation (=how to use it) for all clients should in at questdb.io/docs.

That's problematic, at least for Go client, since the usual approach to have godoc documentation automatically published on https://pkg.go.dev

Yet, we could include a basic client usage snippet into the docs.

**Comment by amyshwang** [comment]
We have improved the landing page in #971
