### ISSUE TITLE
Update - UNION documentation

### ISSUE THREAD

**Issue by amyshwang** [questdb/questdb.io#928]
**Describe the requested changes:**

Set operations to be completed:

1. 
union all
union A+B - (intersect A and B)
except  A + B - 2*(intersect A and B)
intersect (A AND B)
union distinct - union of (distinct A and distinct B)

2
UNIION does type casting for things like - 
```
select double, string from A
union all
select long, string from B
```

Generate a table with all the data types similar to 
https://www.mssqltips.com/sqlservertip/6874/sql-cast-function-for-data-type-conversions/

![image](https://user-images.githubusercontent.com/107401731/177789225-1321bafc-ddc8-4eb2-b002-b098569960de.png)

3
Execution order - top down, dealing with two at the same time 

```
(
select double, string from A
union all
select long, string from B
)
except
select string, string C
```
4 
```
select double x, string from A
union all
select long y, string from B
````
 x and y --> first would be used so x in this example (x would be used to displace the name, as it is the top one)

5. Key word execution order changes when using UNION operation

```
select x, string from A
union all
select y, string from B
order by 1
limit 10
```

is executed as
```(
select x, string from A
union all
select y, string from B
)
order by 1
limit 10
```

While
```select x, string from A
union all
select y, string from B
where y = 10

is executed as
```
select x, string from A
union all
(
select y, string from B
where y = 10
)
**To-do**
1. Play with the operations to ensure that examples are clear 
2. Generate a table to start type casting discussion (which ones are explicit, implicit, not permitted...)
3. Execution order - how to describe these rules?

**Comment by bluestreak01** [comment]
This is how SQL is documented in postgresql: https://www.postgresql.org/docs/current/queries-union.html

**Comment by bluestreak01** [comment]
this is how type conversion is mentioned in postgres doc: https://www.postgresql.org/docs/current/typeconv-union-case.html
