### ISSUE TITLE
Outdated info on the last() aggregation

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb.io#964]
**Describe the requested changes:**
The [docs says](https://questdb.io/docs/reference/function/aggregation/#last) that the last aggregations work on symbol types only. 

![image](https://user-images.githubusercontent.com/158619/181450711-ad96f7a4-f4a1-4da3-8768-25fd9b443dd5.png)

But there is an implementation for other types too: 
![image](https://user-images.githubusercontent.com/158619/181451008-e5fd9330-95ce-4efd-8a2b-b56ca5deeb1e.png)

The documentation should be updated.

**Location:**
https://questdb.io/docs/reference/function/aggregation/#last

Kudos to Stefan S. for [reporting this](https://questdb.slack.com/archives/C1NFJEER0/p1658993636723769).

**Comment by jerrinot** [comment]
it could be nice also to describe behaviour on a table without a designated timestamp. 
See the discussion: https://questdb.slack.com/archives/C1NFJEER0/p1658995082932059?thread_ts=1658993636.723769&cid=C1NFJEER0

**Comment by amyshwang** [comment]
Fixed by #973
