### ISSUE TITLE
Update - Clearer docs for `SYMBOL` and `INDEX` when info covers more than one topic

### ISSUE THREAD

**Issue by amyshwang** [questdb/questdb.io#988]
**Describe the requested changes:**

1. Feedback from @javier:

If I go to the [Symbol page](https://questdb.io/docs/concept/symbol) I see the info about symbols, but if I want to learn more about [index](https://questdb.io/docs/concept/indexes/)ing I have links both to index and [create table](https://questdb.io/docs/reference/sql/create-table/). I go to index, expecting to find ALL the info about indexes there. But not really. Index tells me a generic overview about indexes in a database, but if I want to really know about index parameters and QuestDB specific info about indexes, I can find it only at the create table page, where index capacity is discussed. Not only that, but on that page I find that there is also the CACHE option for Symbols, which is not related to index, but was not referenced at the Symbols page. Bottomline here is that it is difficult to get the full picture about symbols or indexes, and the only way to do it is on the create table page, which is probably not what I would expect. I have seen this pattern in some other functionalities as well

 2. Cloud user Ventura - Setting partitions and schema with symbols properly is still not well understood
 
**Location:**
TBD

**Comment by amyshwang** [comment]
Another relevant page: - https://deploy-preview-987--unruffled-blackwell-31bfb2.netlify.app/docs/operations/capacity-planning

**Comment by bziobrowski** [comment]
cache - if true then symbol values are cached in java heap (as opposed to mapped file memory) so they should be faster to retrieve 
It doesn't depend on index clause in any way .

**Comment by bziobrowski** [comment]
capacity - refers to index file used for checking symbol uniqueness . If capacity declared  in table definition is much lower than actual (in data) then uniqueness check slows down .

**Comment by puzpuzpuz** [comment]
```sql
CREATE TABLE
  my_table(symb SYMBOL capacity 64 cache index capacity 256,
  price DOUBLE, ts TIMESTAMP, s STRING)
  timestamp(ts)
PARTITION BY DAY;
```

There are two different capacities involved:
1. Symbol capacity (64 in the above example). That's an upper bound for the expected count of distinct symbol values. To make things simpler to understand, think of it as the number of buckets in a hash table - if you set it to a too low value, your lookups might end up with O(n) algorithmic complexity. Symbol capacity is also used to set the initial symbol cache size when the cache is enabled for column.
2. Index capacity (256 in the above example). This one defines the size of buckets (a hybrid array list element, to be more precise) in the index files. I'd not suggest to change the default value for this one unless users really know what they're doing (see https://github.com/questdb/questdb/issues/2168).

Needless to say that both of these values are persisted in the table metadata, separately for each column.
